//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagistrOsn
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradesOfStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GradesOfStudent()
        {
            this.StudentsOfGroup = new HashSet<StudentsOfGroup>();
        }
    
        public int idGrade { get; set; }
        public int student { get; set; }
        public int activity { get; set; }
        public int grage { get; set; }
        public bool visit { get; set; }
        public System.DateTime dateActivity { get; set; }
        public System.TimeSpan timeActivity { get; set; }
    
        public virtual Activity Activity1 { get; set; }
        public virtual ClassBook ClassBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsOfGroup> StudentsOfGroup { get; set; }
    }
}
