//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagistrOsn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MagistrDBEntities : DbContext
    {
        public MagistrDBEntities()
            : base("name=MagistrDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<ClassBook> ClassBook { get; set; }
        public virtual DbSet<GradesOfStudent> GradesOfStudent { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Pasport> Pasport { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentsOfGroup> StudentsOfGroup { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Topic> Topic { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<Сourse> Сourse { get; set; }
    }
}
