//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagistrOsn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.Сourse = new HashSet<Сourse>();
        }
    
        public int TabNum { get; set; }
        public string Name { get; set; }
        public System.DateTime dateStartJob { get; set; }
        public decimal salary { get; set; }
        public int position { get; set; }
        public string password { get; set; }

        public string Stazh { get {
                TimeSpan days = DateTime.Now - dateStartJob;
                int years = days.Days / 365;
                int month = (days.Days - (years * 365)) / 30;
                return $"{years} лет {month} мес.";
            } }

        public string TitlePosition { get {
                if (Positions == null)
                    return "";
                else
                    return
                        Positions.Title;
            } }
        public virtual Positions Positions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сourse> Сourse { get; set; }
    }
}
